/************************************
* CPSC471 - Group 19
* Project: P2P
* Database creation/seeding
* Developer: Ahmad Naveed Sorush & Lauren Howard
************************************/

USE master;
GO

-- Create the database

CREATE DATABASE P2P
ON 
( NAME = P2P_dat,
    FILENAME = 'C:\P2P\DB\p2pdat.mdf',
    SIZE = 10,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 5 )
LOG ON
( NAME = Sales_log,
    FILENAME = 'C:\P2P\DB\p2plog.ldf',
    SIZE = 5MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 5MB ) ;
GO

-- Switch to the newly created database
USE [P2P];
GO

-- Create schema
CREATE SCHEMA common;
GO

----------------- INSTITUTIONS ----------------------
CREATE TABLE [common].[INSTITUTIONS] (
	[PK_INSTITUTION_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar] (50) NOT NULL,
	[DOMAIN] [nvarchar] (50) NOT NULL,
	[COUNTRY] [nvarchar](50) NULL,
	[PROVINCE] [nvarchar](50) NULL,
	[CITY] [nvarchar](50) NULL,
	[POSTAL_CODE] [nvarchar](100) NULL,
	[STREET_ADDRESS] [nvarchar](100) NULL,
	[DT_CREATED] [datetime] NOT NULL CONSTRAINT [INSTITUTION_DT_CREATED]  DEFAULT (getutcdate()),
CONSTRAINT [PK_INSTITUTION_ID] PRIMARY KEY CLUSTERED
(
	[PK_INSTITUTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

----------------- USERS ----------------------
CREATE TABLE [common].[USERS] (
	[PK_USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[PASSWORD] [nvarchar](50) NOT NULL,
	[FIRST_NAME] [nvarchar](50) NULL,
	[LAST_NAME] [nvarchar](50) NULL,
	[MIDDLE_NAME] [nvarchar](50) NULL,
	[BRIEF_BIO] [nvarchar](100) NULL,
	[EMAIL] [nvarchar](100) NULL,
	[USER_TYPE] [char] NULL,
	[STAFF_ID] [nvarchar](20) NULL,
	[STAFF_POSITION] [nvarchar](20) NULL,
	[STUDENT_ID] [nvarchar](50) NULL,
	[STUDENT_PROGRAM] [nvarchar](50) NULL,
	[STUDENT_YEAR] int NULL,
	[STUDENT_LEVEL] [nvarchar](50) NULL,
	[INSTITUTION_ID] int NOT NULL,
	[DT_CREATED] [datetime] NOT NULL CONSTRAINT [USER_DT_CREATED]  DEFAULT (getutcdate()),
CONSTRAINT [PK_USER_ID] PRIMARY KEY CLUSTERED
(
	[PK_USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
ALTER TABLE [common].[USERS]  WITH CHECK ADD  CONSTRAINT [FK_INSTITUTION_ID] FOREIGN KEY([INSTITUTION_ID])
REFERENCES [common].[INSTITUTIONS] ([PK_INSTITUTION_ID])
GO
ALTER TABLE [common].[USERS] CHECK CONSTRAINT [FK_INSTITUTION_ID]
GO

----------------- GROUPS ----------------------
CREATE TABLE [common].[GROUPS](
	[PK_GROUP_ID] [int] IDENTITY(1,1) NOT NULL,
	[GROUP_OWNER_USER_ID] [int] NOT NULL,
	[NAME] [nvarchar](100) NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[DT_CREATED] [datetime] NOT NULL CONSTRAINT [GROUPS_DT_CREATED]  DEFAULT (getutcdate()),
CONSTRAINT [PK_GROUP_ID] PRIMARY KEY CLUSTERED
(
	[PK_GROUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [common].[GROUPS]  WITH CHECK ADD  CONSTRAINT [FK_GROUPS_USERS] FOREIGN KEY([GROUP_OWNER_USER_ID])
REFERENCES [common].[USERS] ([PK_USER_ID])
GO
ALTER TABLE [common].[GROUPS] CHECK CONSTRAINT [FK_GROUPS_USERS]
GO

----------------- SIGNIN ----------------------
CREATE TABLE [common].[SIGNIN](
	[PK_SIGNIN_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[SESSION_IS_ACTIVE] [bit] NULL,
	[DT_CREATED] [datetime] NOT NULL CONSTRAINT [SIGNIN_DT_CREATED]  DEFAULT (getutcdate()),
CONSTRAINT [PK_SIGNIN_ID] PRIMARY KEY CLUSTERED
(
	[PK_SIGNIN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [common].[SIGNIN]  WITH CHECK ADD  CONSTRAINT [FK_USER_ID] FOREIGN KEY([USER_ID])
REFERENCES [common].[USERS] ([PK_USER_ID])
GO
ALTER TABLE [common].[SIGNIN] CHECK CONSTRAINT [FK_USER_ID]
GO

----------------- TAGS ----------------------
CREATE TABLE [common].[TAGS](
	[PK_TAG_ID] [int] IDENTITY(1,1) NOT NULL,
	[VALUE] [nvarchar](100) NULL,
	[DT_CREATED] [datetime] NOT NULL CONSTRAINT [TAG_DT_CREATED]  DEFAULT (getutcdate()),
CONSTRAINT [PK_TAG_ID] PRIMARY KEY CLUSTERED
(
	[PK_TAG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
